/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DResult: typeof import('./../components/DResult.vue')['default']
    Dropdown: typeof import('./../components/Dropdown/index.vue')['default']
    DTabs: typeof import('./../components/DTabs/index.vue')['default']
    DUpload: typeof import('./../components/DUpload.vue')['default']
    EditDialog: typeof import('./../components/EditDialog/index.vue')['default']
    EditMenuItemForm: typeof import('./../components/EditMenuItemForm.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElTag: typeof import('element-plus/es')['ElTag']
    Error: typeof import('./../components/Error/index.vue')['default']
    FormItem: typeof import('./../components/EditDialog/FormItem.vue')['default']
    IEpEditPen: typeof import('~icons/ep/edit-pen')['default']
    Layout: typeof import('./../components/Layout.vue')['default']
    LayoutBase: typeof import('./../components/LayoutBase/index.vue')['default']
    MenuTag: typeof import('./../components/MenuTag/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./../components/sidebar/index.vue')['default']
  }
}
